name: GitHub Actions Demo
run-name: ${{ github.actor }} is running unit tests 🚀
on: [push]
jobs:
  Unit tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
              npm ci
              ./node_modules/.bin/vitest run