name: Vue Demo
run-name: ${{ github.actor }} is running unit tests 🚀
on: [push]
jobs:
  unit-tests:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
              npm ci
              ./node_modules/.bin/vitest run